name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy to GitHub Pages
        run: |
          echo "Deploying to GitHub Pages from main branch"
          echo "Make sure to configure GitHub Pages to deploy from main branch"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          
          # This workflow just ensures the main branch is up to date
          # GitHub Pages will automatically deploy from the main branch
          # when configured in repository settings
